select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)


--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,
avg(review_rating)as "Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select Round(avg(purchase_amount),2),shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as average_spend,
Round(sum(purchase_amount),2) as total_spend
from customer
group by subscription_status



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100*sum(case when discount_applied='Yes' then 1 else 0 end) / count (*),2) as Discount_rating
from customer
group by item_purchased
order by Discount_rating desc
limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select
case
   when previous_purchases=1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as Customer_segment,count(*) as customer_count
 from customer
 group by Customer_segment
 order by customer_count desccategory



--Q8. What are the top 3 most purchased products within each category? 
select
category,
item_purchased,
purchase_count
from(
  select
  category,
  item_purchased,
  count(*) as purchase_count,
  rank() over(
      partition by category
	  order by count(*) desc
  )as product_rank
  from customer
  group by category,item_purchased
) as ranked_products
where product_rank <= 3
order by category,product_rank




--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
subscription_status,
count (customer_id)as Repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
order by Repeat_buyers


--Q10. What is the revenue contribution of each age group? I
select
age_grouped,
sum (purchase_amount) as Total_Revenue
from customer
group by age_grouped
order by Total_Revenue desc